# Generated by Django 4.2.11 on 2026-10-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=30)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetectionCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('rule_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('rule_id', models.CharField(max_length=50)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('threshold', models.PositiveIntegerField()),
                ('observed_count', models.PositiveIntegerField()),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('detected_at', models.DateTimeField()),
                ('evidence', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('disposition', models.CharField(blank=True, choices=[('true_positive', 'True positive'), ('false_positive', 'False positive'), ('benign', 'Benign')], max_length=20)),
                ('closure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation', to='app.detectionfinding')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='app.investigation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='detectionfinding',
            index=models.Index(fields=['ip_address', 'rule_id', 'detected_at'], name='app_detecti_ip_addr_dc1175_idx'),
        ),
        migrations.AddField(
            model_name='detectioncursor',
            name='finding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.detectionfinding'),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='app.investigation'),
        ),
        migrations.AddConstraint(
            model_name='detectioncursor',
            constraint=models.UniqueConstraint(fields=('ip_address', 'rule_id'), name='unique_source_rule_cursor'),
        ),
    ]
