# Generated by Django 4.2.11 on 2026-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_roles(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    for name in ['Analysts', 'Viewers']:
        group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auditentry_detectioncursor_detectionfinding_and_more'),
    ]

    operations = [
        migrations.RunPython(create_roles, migrations.RunPython.noop),
        migrations.AddField(
            model_name='auditentry',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigation_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationnote',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigation_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccessAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_changes', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
