# Generated by Django 5.2.18 on 2026-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auditentry_actor_user_investigation_owner_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
